targets:
  $default:
    sources:
      exclude:
        - /lib/features/core/data/response/dynamic_response/**.dart
        - /lib/features/core/data/response/dynamic_response/**
        - /lib/features/core/data/response/dynamic_response/
    builders:
      json_serializable:
        options:
          create_to_json: true
          explicit_to_json: true
          include_if_null: false
      freezed:
        options:
          union_key: type
          union_value_case: snake
