name: Debug workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: true
        default: 1.0.0

  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build apk for testing
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Nafta Credit"
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Fetch Repo HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java Environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare NDK dir for caching
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk

      - name: Cache Android NDK
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ndk-cache-21.0.6113669-v2

      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Run Pre-build scipts
        run: |
          flutter pub get
          # flutter test

      - name: Build Flutter Apk
        run: |
          flutter build apk -t lib/main.dart --release --target-platform android-arm,android-arm64 --split-per-abi --flavor=prod --obfuscate --split-debug-info=./build/app/outputs/apk/obfuscation --dart-define=BUILD_NUMBER=$BUILD_NUMBER --dart-define=BUILD_VERSION=$BUILD_VERSION --dart-define=BUILD_COMMIT=$FCI_COMMIT

      - name: Bump version and push tag
        id: bump_tag
        if: ${{ github.event.inputs.version == '' }}
        uses: mathieudutour/github-tag-action@v4.5
        with:
          release_branches: .*
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Environment variables
        run: |
          if ${{ github.event.inputs.version == '' }}; then
            echo "BUMP_TAG=${{ steps.bump_tag.outputs.new_tag }}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ steps.bump_tag.outputs.new_version }}" >> $GITHUB_ENV
          else
            echo "BUMP_TAG=v${{ github.event.inputs.version}}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ github.event.inputs.version}}" >> $GITHUB_ENV
          fi

      - name: Push APK to Release Tags
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/prod/release/*.apk,build/app/outputs/apk/release/*.apk,build/app/outputs/apk/*"
          name: ${{ env.APP_NAME }}-${{ env.BUMP_VERSION }}
          tag: ${{ env.BUMP_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitName: false
          omitBody: false
