name: Production Release Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: true
        default: 1.0.0

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release
    types:
      - opened
      - reopened
      - closed
      - synchronize
      - closed

jobs:
  build:
    name: Build & Deploy Production APK
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Nafta Credit"
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    outputs:
      bump_tag: ${{ env.BUMP_TAG }}
      bump_tag_version: ${{ env.BUMP_VERSION }}
    steps:
      - name: Fetch Repo HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java Environment
        uses: actions/setup-java@v1
        with:
          java-version: "16.0.1"

      - name: Prepare NDK dir for caching
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk

      - name: Cache Android NDK
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ndk-cache-21.0.6113669-v2

      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Run Pre-build scipts
        run: |
          flutter pub get
          # flutter test

      - name: Build Flutter Apk
        run: |
          flutter build apk -t lib/main.dart --release --target-platform android-arm,android-arm64 --split-per-abi --flavor prod --obfuscate --split-debug-info=./build/app/outputs/apk/obfuscation

      - name: Bump version and push tag
        id: bump_tag
        if: ${{ github.event.inputs.version == '' }}
        uses: mathieudutour/github-tag-action@v4.5
        with:
          release_branches: .*
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Environment variables
        run: |
          if ${{ github.event.inputs.version == '' }}; then
            echo "BUMP_TAG=${{ steps.bump_tag.outputs.new_tag }}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ steps.bump_tag.outputs.new_version }}" >> $GITHUB_ENV
          else
            echo "BUMP_TAG=v${{ github.event.inputs.version}}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ github.event.inputs.version}}" >> $GITHUB_ENV
          fi

      - name: Push APK to Release Tags
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/prod/release/*.apk,build/app/outputs/apk/release/*.apk,build/app/outputs/apk/*"
          name: ${{ env.APP_NAME }}-${{ env.BUMP_VERSION }}
          tag: ${{ env.BUMP_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitName: false
          omitBody: false
  # notify:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   env:
  #     APP_NAME: "Pexza App"
  #     REPOSITORY_NAME: "pexza-app"
  #     API_KEY: ${{ secrets.ZAPIER_TEAM_API_KEY }}
  #   steps:
  #     - name: Send Push Notification
  #       uses: techulus/push-github-action@1.0.0
  #       env:
  #         API_KEY: ${{ env.API_KEY }}
  #         TITLE: Version Bump Notification
  #         MESSAGE: Bump Version ${{ needs.build.outputs.bump_tag_version }} available for download at https://github.com/f0rx/${{ env.REPOSITORY_NAME }}/releases/tag/${{ needs.build.outputs.bump_tag }}
  #         LINK: https://github.com/f0rx/${{ env.REPOSITORY_NAME }}/releases/tag/${{ needs.build.outputs.bump_tag }}
